"""
Report Generator
================
Generate readable reports from job analysis results.

Usage:
    python generate_report.py --input outputs/reports/analysis_latest.json
    python generate_report.py --format html
"""

import sys

# Fix Windows console encoding for emoji support
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

import json
from pathlib import Path
from datetime import datetime
import argparse


class ReportGenerator:
    """Generate reports from analysis results."""
    
    def __init__(self, analysis_data: dict = None):
        self.data = analysis_data or {}
        self.report_content = ""
        
    def load_analysis(self, file_path: str):
        """Load analysis results from JSON file."""
        with open(file_path, 'r', encoding='utf-8') as f:
            self.data = json.load(f)
        print(f"✅ Loaded analysis from {file_path}")
        return self
    
    def generate_markdown(self) -> str:
        """Generate Markdown report."""
        md = []
        
        # Header
        md.append("# 📊 LinkedIn Job Analysis Report\n")
        md.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        
        if 'metadata' in self.data:
            md.append(f"**Total Jobs Analyzed:** {self.data['metadata'].get('total_jobs', 'N/A')}\n")
        
        md.append("---\n")
        
        # Top Job Titles
        if 'top_titles' in self.data:
            md.append("## 🏷️ Top Job Titles\n")
            md.append(f"*{self.data['top_titles'].get('total_unique', 0)} unique titles found*\n")
            md.append("| Rank | Job Title | Count |")
            md.append("|------|-----------|-------|")
            for i, (title, count) in enumerate(self.data['top_titles']['data'].items(), 1):
                md.append(f"| {i} | {title} | {count} |")
            md.append("")
        
        # Top Companies
        if 'top_companies' in self.data:
            md.append("## 🏢 Top Hiring Companies\n")
            md.append(f"*{self.data['top_companies'].get('total_unique', 0)} unique companies*\n")
            md.append("| Rank | Company | Open Positions |")
            md.append("|------|---------|----------------|")
            for i, (company, count) in enumerate(self.data['top_companies']['data'].items(), 1):
                md.append(f"| {i} | {company} | {count} |")
            md.append("")
        
        # Top Locations
        if 'top_locations' in self.data:
            md.append("## 📍 Top Locations\n")
            md.append("| Rank | Location | Jobs |")
            md.append("|------|----------|------|")
            for i, (loc, count) in enumerate(self.data['top_locations']['data'].items(), 1):
                md.append(f"| {i} | {loc} | {count} |")
            md.append("")
        
        # Skills Analysis
        if 'skills' in self.data:
            md.append("## 🔧 In-Demand Skills\n")
            md.append("| Rank | Skill | Mentions |")
            md.append("|------|-------|----------|")
            for i, (skill, count) in enumerate(self.data['skills'].get('top_10', {}).items(), 1):
                md.append(f"| {i} | {skill.upper()} | {count} |")
            md.append("")
        
        # Experience Levels
        if 'experience_levels' in self.data:
            md.append("## 📈 Experience Level Distribution\n")
            md.append("| Level | Jobs |")
            md.append("|-------|------|")
            for level, count in self.data['experience_levels'].items():
                md.append(f"| {level} | {count} |")
            md.append("")
        
        # Job Types
        if 'job_types' in self.data:
            md.append("## 💼 Job Types\n")
            md.append("| Type | Count |")
            md.append("|------|-------|")
            for jtype, count in self.data['job_types'].items():
                if count > 0:
                    md.append(f"| {jtype} | {count} |")
            md.append("")
        
        # Salary Info
        if 'salary' in self.data:
            md.append("## 💰 Salary Information\n")
            salary_data = self.data['salary']
            if 'total_mentions' in salary_data:
                md.append(f"- **Salary mentions found:** {salary_data['total_mentions']}\n")
            if 'samples_found' in salary_data and salary_data['samples_found']:
                md.append("**Sample salary ranges:**\n")
                for sample in salary_data['samples_found'][:5]:
                    md.append(f"- {sample}")
            md.append("")
        
        # Footer
        md.append("---\n")
        md.append("*Report generated by LinkedIn Job Analysis Tool*\n")
        
        self.report_content = "\n".join(md)
        return self.report_content
    
    def generate_html(self) -> str:
        """Generate HTML report."""
        # First generate markdown, then convert to HTML
        md_content = self.generate_markdown()
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LinkedIn Job Analysis Report</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
            color: #333;
        }}
        .container {{
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        h1 {{ color: #0077b5; border-bottom: 3px solid #0077b5; padding-bottom: 10px; }}
        h2 {{ color: #333; margin-top: 30px; }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        th, td {{
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }}
        th {{
            background: #0077b5;
            color: white;
        }}
        tr:hover {{ background: #f5f5f5; }}
        .stat-box {{
            display: inline-block;
            background: #e8f4f8;
            padding: 15px 25px;
            border-radius: 8px;
            margin: 10px 10px 10px 0;
        }}
        .stat-number {{ font-size: 24px; font-weight: bold; color: #0077b5; }}
        .stat-label {{ font-size: 12px; color: #666; }}
        .footer {{ text-align: center; color: #888; margin-top: 30px; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 LinkedIn Job Analysis Report</h1>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        
        {self._generate_html_stats()}
        {self._generate_html_tables()}
        
        <div class="footer">
            <p>Report generated by LinkedIn Job Analysis Tool</p>
        </div>
    </div>
</body>
</html>"""
        
        self.report_content = html
        return html
    
    def _generate_html_stats(self) -> str:
        """Generate HTML stat boxes."""
        stats = []
        
        if 'metadata' in self.data:
            stats.append(f"""
            <div class="stat-box">
                <div class="stat-number">{self.data['metadata'].get('total_jobs', 0)}</div>
                <div class="stat-label">Total Jobs</div>
            </div>""")
        
        if 'top_titles' in self.data:
            stats.append(f"""
            <div class="stat-box">
                <div class="stat-number">{self.data['top_titles'].get('total_unique', 0)}</div>
                <div class="stat-label">Unique Titles</div>
            </div>""")
        
        if 'top_companies' in self.data:
            stats.append(f"""
            <div class="stat-box">
                <div class="stat-number">{self.data['top_companies'].get('total_unique', 0)}</div>
                <div class="stat-label">Companies Hiring</div>
            </div>""")
        
        if 'skills' in self.data:
            stats.append(f"""
            <div class="stat-box">
                <div class="stat-number">{len(self.data['skills'].get('data', {}))}</div>
                <div class="stat-label">Skills Identified</div>
            </div>""")
        
        return "\n".join(stats)
    
    def _generate_html_tables(self) -> str:
        """Generate HTML tables for each section."""
        sections = []
        
        # Top Skills
        if 'skills' in self.data and self.data['skills'].get('top_10'):
            rows = "".join([
                f"<tr><td>{i}</td><td>{skill.upper()}</td><td>{count}</td></tr>"
                for i, (skill, count) in enumerate(self.data['skills']['top_10'].items(), 1)
            ])
            sections.append(f"""
            <h2>🔧 Top In-Demand Skills</h2>
            <table>
                <tr><th>#</th><th>Skill</th><th>Mentions</th></tr>
                {rows}
            </table>""")
        
        # Top Companies
        if 'top_companies' in self.data:
            rows = "".join([
                f"<tr><td>{i}</td><td>{company}</td><td>{count}</td></tr>"
                for i, (company, count) in enumerate(list(self.data['top_companies']['data'].items())[:10], 1)
            ])
            sections.append(f"""
            <h2>🏢 Top Hiring Companies</h2>
            <table>
                <tr><th>#</th><th>Company</th><th>Open Positions</th></tr>
                {rows}
            </table>""")
        
        # Top Locations
        if 'top_locations' in self.data:
            rows = "".join([
                f"<tr><td>{i}</td><td>{loc}</td><td>{count}</td></tr>"
                for i, (loc, count) in enumerate(list(self.data['top_locations']['data'].items())[:10], 1)
            ])
            sections.append(f"""
            <h2>📍 Top Locations</h2>
            <table>
                <tr><th>#</th><th>Location</th><th>Jobs</th></tr>
                {rows}
            </table>""")
        
        return "\n".join(sections)
    
    def save_report(self, output_path: str = None, format: str = 'markdown'):
        """Save report to file."""
        output_dir = Path('d:/Linkedin-Job-Analysis/outputs/reports')
        output_dir.mkdir(parents=True, exist_ok=True)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        if format == 'html':
            if not output_path:
                output_path = output_dir / f'report_{timestamp}.html'
            content = self.generate_html()
        else:
            if not output_path:
                output_path = output_dir / f'report_{timestamp}.md'
            content = self.generate_markdown()
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"📄 Report saved to: {output_path}")
        return output_path


def find_latest_analysis():
    """Find the most recent analysis file."""
    reports_dir = Path('d:/Linkedin-Job-Analysis/outputs/reports')
    
    if not reports_dir.exists():
        return None
    
    files = list(reports_dir.glob('analysis_*.json'))
    
    if not files:
        return None
    
    return max(files, key=lambda f: f.stat().st_mtime)


def main():
    parser = argparse.ArgumentParser(description='Generate job analysis report')
    parser.add_argument('--input', '-i', type=str, help='Input analysis JSON file')
    parser.add_argument('--output', '-o', type=str, help='Output report file path')
    parser.add_argument('--format', '-f', choices=['markdown', 'html'], default='markdown',
                       help='Output format (default: markdown)')
    
    args = parser.parse_args()
    
    # Find analysis file
    analysis_file = args.input if args.input else find_latest_analysis()
    
    if not analysis_file:
        print("❌ No analysis file found. Run analyze_jobs.py first.")
        return
    
    # Generate report
    generator = ReportGenerator()
    generator.load_analysis(analysis_file)
    generator.save_report(args.output, args.format)
    
    print("\n✨ Report generation complete!")


if __name__ == "__main__":
    main()
