"""
Notification Manager
====================
Send job alerts and reports via Email, Slack, Discord.

Usage:
    python notification_manager.py --test-email         # Test email
    python notification_manager.py --test-slack         # Test Slack
    python notification_manager.py --send-report        # Send daily report
"""

import sys

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional
import argparse

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False

try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
CONFIG_FILE = PROJECT_ROOT / 'config' / 'settings.yaml'
REPORTS_DIR = PROJECT_ROOT / 'outputs' / 'reports'
ALERTS_FILE = PROJECT_ROOT / 'outputs' / 'reports' / 'alert_matches.json'


class NotificationManager:
    """Manage notifications across different platforms."""
    
    def __init__(self):
        self.config = self._load_config()
    
    def _load_config(self) -> Dict:
        """Load configuration."""
        if HAS_YAML and CONFIG_FILE.exists():
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                return yaml.safe_load(f) or {}
        return {}
    
    def _load_latest_analysis(self) -> Dict:
        """Load most recent analysis."""
        files = list(REPORTS_DIR.glob('analysis_*.json'))
        if files:
            latest = max(files, key=lambda f: f.stat().st_mtime)
            with open(latest, 'r', encoding='utf-8') as f:
                return json.load(f)
        return {}
    
    def _load_alert_matches(self) -> Dict:
        """Load alert matches."""
        if ALERTS_FILE.exists():
            with open(ALERTS_FILE, 'r', encoding='utf-8') as f:
                return json.load(f)
        return {}
    
    def _generate_report_text(self) -> str:
        """Generate text report for notifications."""
        analysis = self._load_latest_analysis()
        alerts = self._load_alert_matches()
        
        report = []
        report.append("=" * 50)
        report.append("LINKEDIN JOB ANALYSIS - DAILY REPORT")
        report.append(f"Date: {datetime.now().strftime('%Y-%m-%d')}")
        report.append("=" * 50)
        
        # Summary
        metadata = analysis.get('metadata', {})
        report.append(f"\nTotal Jobs Analyzed: {metadata.get('total_jobs', 0)}")
        report.append(f"Companies Hiring: {analysis.get('top_companies', {}).get('total_unique', 0)}")
        
        # Top Skills
        top_skills = list(analysis.get('skills', {}).get('top_10', {}).items())[:5]
        if top_skills:
            report.append("\nTop Skills in Demand:")
            for skill, count in top_skills:
                report.append(f"  - {skill.upper()}: {count} jobs")
        
        # Alert Matches
        if alerts.get('alerts'):
            report.append("\nJob Alert Matches:")
            for alert_name, data in alerts['alerts'].items():
                count = data.get('count', 0)
                if count > 0:
                    report.append(f"  [!] {alert_name}: {count} matches")
        
        report.append("\n" + "=" * 50)
        report.append("Generated by LinkedIn Job Analysis Tool")
        
        return "\n".join(report)
    
    def _generate_report_html(self) -> str:
        """Generate HTML report for email."""
        analysis = self._load_latest_analysis()
        alerts = self._load_alert_matches()
        
        metadata = analysis.get('metadata', {})
        top_skills = list(analysis.get('skills', {}).get('top_10', {}).items())[:5]
        
        skills_rows = "".join([
            f"<tr><td>{skill.upper()}</td><td>{count}</td></tr>"
            for skill, count in top_skills
        ])
        
        alert_rows = ""
        if alerts.get('alerts'):
            for alert_name, data in alerts['alerts'].items():
                count = data.get('count', 0)
                if count > 0:
                    alert_rows += f"<tr><td>{alert_name}</td><td>{count} matches</td></tr>"
        
        html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; padding: 20px; }}
                h1 {{ color: #0077B5; }}
                table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
                th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
                th {{ background-color: #0077B5; color: white; }}
                .stat {{ font-size: 24px; font-weight: bold; color: #0077B5; }}
            </style>
        </head>
        <body>
            <h1>LinkedIn Job Analysis Report</h1>
            <p>Date: {datetime.now().strftime('%Y-%m-%d')}</p>
            
            <h2>Summary</h2>
            <p><span class="stat">{metadata.get('total_jobs', 0)}</span> Total Jobs</p>
            <p><span class="stat">{analysis.get('top_companies', {}).get('total_unique', 0)}</span> Companies Hiring</p>
            
            <h2>Top Skills in Demand</h2>
            <table>
                <tr><th>Skill</th><th>Jobs</th></tr>
                {skills_rows}
            </table>
            
            {f'<h2>Job Alert Matches</h2><table><tr><th>Alert</th><th>Matches</th></tr>{alert_rows}</table>' if alert_rows else ''}
            
            <hr>
            <p style="color: #888; font-size: 12px;">Generated by LinkedIn Job Analysis Tool</p>
        </body>
        </html>
        """
        return html
    
    def send_email(self, to_email: str = None, subject: str = None, 
                   body: str = None, html: bool = True, attachment: str = None) -> bool:
        """Send email notification."""
        email_config = self.config.get('email', {})
        
        if not email_config.get('sender_email') or not email_config.get('sender_password'):
            print("[X] Email not configured. Update config/settings.yaml")
            return False
        
        to_email = to_email or email_config.get('recipient_email')
        if not to_email:
            print("[X] No recipient email specified")
            return False
        
        subject = subject or f"LinkedIn Job Analysis Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        try:
            msg = MIMEMultipart('alternative')
            msg['From'] = email_config['sender_email']
            msg['To'] = to_email
            msg['Subject'] = subject
            
            # Body
            if body:
                if html:
                    msg.attach(MIMEText(body, 'html'))
                else:
                    msg.attach(MIMEText(body, 'plain'))
            else:
                # Generate default report
                msg.attach(MIMEText(self._generate_report_text(), 'plain'))
                msg.attach(MIMEText(self._generate_report_html(), 'html'))
            
            # Attachment
            if attachment and Path(attachment).exists():
                with open(attachment, 'rb') as f:
                    part = MIMEBase('application', 'octet-stream')
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    part.add_header('Content-Disposition', 
                                  f'attachment; filename={Path(attachment).name}')
                    msg.attach(part)
            
            # Send
            server = smtplib.SMTP(
                email_config.get('smtp_server', 'smtp.gmail.com'),
                email_config.get('smtp_port', 587)
            )
            server.starttls()
            server.login(email_config['sender_email'], email_config['sender_password'])
            server.send_message(msg)
            server.quit()
            
            print(f"[OK] Email sent to: {to_email}")
            return True
            
        except Exception as e:
            print(f"[X] Email failed: {e}")
            return False
    
    def send_slack(self, webhook_url: str = None, message: str = None) -> bool:
        """Send Slack notification."""
        if not HAS_REQUESTS:
            print("[X] requests required: pip install requests")
            return False
        
        webhook_url = webhook_url or self.config.get('slack', {}).get('webhook_url')
        if not webhook_url:
            print("[X] Slack webhook URL not configured")
            return False
        
        if not message:
            message = self._generate_report_text()
        
        # Format for Slack
        payload = {
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "LinkedIn Job Analysis Report"
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": message.replace("=", "").strip()
                    }
                }
            ]
        }
        
        try:
            response = requests.post(webhook_url, json=payload)
            if response.status_code == 200:
                print("[OK] Slack message sent")
                return True
            else:
                print(f"[X] Slack failed: {response.status_code}")
                return False
        except Exception as e:
            print(f"[X] Slack error: {e}")
            return False
    
    def send_discord(self, webhook_url: str = None, message: str = None) -> bool:
        """Send Discord notification."""
        if not HAS_REQUESTS:
            print("[X] requests required: pip install requests")
            return False
        
        webhook_url = webhook_url or self.config.get('discord', {}).get('webhook_url')
        if not webhook_url:
            print("[X] Discord webhook URL not configured")
            return False
        
        if not message:
            message = self._generate_report_text()
        
        # Discord has 2000 char limit
        if len(message) > 1900:
            message = message[:1900] + "\n..."
        
        payload = {
            "content": f"```\n{message}\n```",
            "username": "Job Analysis Bot"
        }
        
        try:
            response = requests.post(webhook_url, json=payload)
            if response.status_code in [200, 204]:
                print("[OK] Discord message sent")
                return True
            else:
                print(f"[X] Discord failed: {response.status_code}")
                return False
        except Exception as e:
            print(f"[X] Discord error: {e}")
            return False
    
    def send_job_alert(self, alert_name: str, jobs: List[Dict]) -> bool:
        """Send job alert notification."""
        if not jobs:
            return False
        
        message = f"Job Alert: {alert_name}\n"
        message += f"Found {len(jobs)} matching jobs:\n\n"
        
        for i, job in enumerate(jobs[:5], 1):
            message += f"{i}. {job.get('title', 'N/A')}\n"
            message += f"   Company: {job.get('company', 'N/A')}\n"
            message += f"   Location: {job.get('location', 'N/A')}\n\n"
        
        if len(jobs) > 5:
            message += f"... and {len(jobs) - 5} more\n"
        
        # Try all configured channels
        sent = False
        
        if self.config.get('email', {}).get('enabled'):
            sent = self.send_email(body=message, html=False) or sent
        
        if self.config.get('slack', {}).get('webhook_url'):
            sent = self.send_slack(message=message) or sent
        
        if self.config.get('discord', {}).get('webhook_url'):
            sent = self.send_discord(message=message) or sent
        
        return sent


def main():
    parser = argparse.ArgumentParser(description='Notification Manager')
    parser.add_argument('--test-email', action='store_true', help='Test email notification')
    parser.add_argument('--test-slack', action='store_true', help='Test Slack notification')
    parser.add_argument('--test-discord', action='store_true', help='Test Discord notification')
    parser.add_argument('--send-report', action='store_true', help='Send daily report')
    parser.add_argument('--to', type=str, help='Recipient email')
    parser.add_argument('--webhook', type=str, help='Webhook URL for Slack/Discord')
    
    args = parser.parse_args()
    
    manager = NotificationManager()
    
    if args.test_email:
        manager.send_email(to_email=args.to)
    elif args.test_slack:
        manager.send_slack(webhook_url=args.webhook)
    elif args.test_discord:
        manager.send_discord(webhook_url=args.webhook)
    elif args.send_report:
        print("\n[i] Sending daily report to all configured channels...")
        if manager.config.get('email', {}).get('enabled'):
            manager.send_email()
        if manager.config.get('slack', {}).get('webhook_url'):
            manager.send_slack()
        if manager.config.get('discord', {}).get('webhook_url'):
            manager.send_discord()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
